name: jacoco-pages
on:
  push:
    branches: [ lab2 ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Test + JaCoCo report
        run: ./gradlew --no-daemon clean test jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true